name = "awhoslst"
main = "worker.js"
compatibility_date = "2024-12-01"
workers_dev = true
preview_urls = true

routes = [
  { pattern = "nordicnfas.com", custom_domain = true }
]

[assets]
directory = "./public"
binding = "ASSETS"
